### ISSUE TITLE
ActiveQueryInterface not available in Yii1

### ISSUE THREAD

**Issue by OndicsTA** [ondics/yii1spreadsheet#1]
Do we have ActiveQueryInterface in Yii1? Probably not. Maybe not migrated from Yii2?

https://github.com/ondics/yii1spreadsheet/blob/a29cbe25e4ff0755ca907e62bc3ee81aa991ade4/src/DataColumn.php#L87

This should be sufficient:

    if ($provider instanceof CActiveDataProvider) {
        ....

**Comment by ondics** [comment]
ok, bug resolved with commit https://github.com/ondics/yii1spreadsheet/commit/6e6205f9e548dae10a18c016479290b8faebafd3

**Comment by OndicsTA** [comment]
Problem is not fixed yet. In output column the attribute name is shown.

**Comment by ondics** [comment]
May this helps for a quick fix:

https://github.com/yiisoft/yii2/issues/5213#issuecomment-57067879

**Comment by ondics** [comment]
fixed again. works now.
